### ISSUE TITLE
Possible storage leak

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#156]
In the past 5 days of testing the custom build, I noticed that occasionally the interactions were not recorded. 

For example, I have noticed that some "likes", "view profile", "shares" were not recorded. First I thought that the observers might have been broken. But later on (sometimes even without re-starting the browser), the interactions of the same kind were recorded. So it is possible that there is a storage leak.

**Comment by YiranWangPARC14** [comment]
I notice some interactions not recorded again about 20 mins ago. I "liked" a post, but not recorded. A few minutes later, I messaged someone, which was recorded as "chat". The subsequent interactions I engaged, such as "unlike", "like" on the same post that was not recorded about 20 mins ago was successfully recorded. I opened the javascript console, and here is the screenshot (I'm not sure if this speaks to the problem), but in case it is helpful.

<img width="551" alt="screen shot 2015-08-17 at 6 41 21 pm" src="https://cloud.githubusercontent.com/assets/3218051/9320523/fd59069e-450f-11e5-8d1e-8a62c98078e6.png">

**Comment by dharma-guardian** [comment]
It seems this is not a storage problem, but a problem of the observer-engine. The unrecorded "like" would still show in the console, if it had been tracked, but not stored. The observers rely on particular elements of the facebook page, so it would be helpful to know, how/where you performed the interaction? Because maybe an observer is not complete.
And did you refresh the page after it did not work? Could explain the console log.

**Comment by dharma-guardian** [comment]
@YiranWangPARC14 Any news? Did it happen again? I compared my activity log on fb with Rose and all missing interactions seem to be from using the mobile application. So, still no sign of a storage leak/observer problem on my side.

**Comment by YiranWangPARC14** [comment]
It haven't happened in the current version. Good sign.
