### ISSUE TITLE
Yiran build 2.0 test notes

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#161]
Things that have been working correctly:

- When log out, survey 2 got immediately triggered.
- When I switched to another non-browser computer app (e.g., excel, word) without logging out of FB, survey 2 triggered after 2 mins, which took me back to the browser to see the pop-up window.
- Survey 1 has been working well!

Hiccups:
- Survey 2 didn’t trigger for 2-3 times on the first day of testing. It had been working fine afterwards. Here are the console logs from the first day when survey 2 wasn't working correctly.

![screen shot 2015-08-19 at 4 42 40 pm](https://cloud.githubusercontent.com/assets/3218051/9430282/9e30922a-49a3-11e5-8c7a-cba6c9648bf7.png)
![screen shot 2015-08-19 at 4 43 54 pm](https://cloud.githubusercontent.com/assets/3218051/9430284/9e3366b2-49a3-11e5-8421-3289b247020f.png)
![screen shot 2015-08-19 at 7 49 31 pm](https://cloud.githubusercontent.com/assets/3218051/9430283/9e3180f4-49a3-11e5-9973-4b16d16b346b.png)

- There was one time when I did not log into FB, but I was on Facebook to see some public pages (you can do that without logging in). While I was still on Facebook, survey 2 triggered. If this is tricky to fix, we don't have to worry about it, as I don't expect the participants to use Facebook without logging in.

**Comment by dharma-guardian** [comment]
@YiranWangPARC14 Could you check #157 for leftovers, add them here and close it? So, we don't have to much duplicates.

It seems the hiccups are due to the way we show survey 2 right now. When you have the console of ROSE open, the browser thinks of it as the active tab, but because there is no actual page, it can not show the alert. So, I think this is can be ignored.

About the other hiccup: I would leave it like that.

**Comment by dharma-guardian** [comment]
@YiranWangPARC14 bump

**Comment by dharma-guardian** [comment]
I think all issues are dealt with. New problems please in a separate issue.
