### ISSUE TITLE
New fb feature called "Notes". Changes for ROSE?

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#195]
So, there is a new feature on facebook called notes. I do not really see what it is for, but we have to check, if all observers work with it.
@YiranWangPARC14 this is related to the renaming of the commenting feature of ROSE, because "notes" would be contradictory as well.

![bildschirmfoto vom 2015-11-19 17 38 16](https://cloud.githubusercontent.com/assets/1899308/11277018/df6bd584-8ee4-11e5-884c-c779579d9280.png)
![bildschirmfoto vom 2015-11-19 17 35 08](https://cloud.githubusercontent.com/assets/1899308/11277017/df64305e-8ee4-11e5-8ce3-6442e1439796.png)

**Comment by YiranWangPARC14** [comment]
Yes, I am aware of the function (that almost nobody uses). It is similar to uploading a photo, or a status update, but in a note, you can write a long article. Of all my friends, I think 2-3 have used it before.

Here are two options (I don't personally have a preference, so it really depends on which on is easier for you):

A. Use "Notes" for the ribbon, and tell participants that this is a different function to FB notes. I suspect that it is going to be fine, as almost nobody uses that function.

B. Use "Diary" for the ribbon, and hide the Diary function on the ROSE UI, so that partticipants won't get confused.

What do you think?

**Comment by apoller** [comment]
What about "Study Note"? Would avoid mistakes in my opinion.

**Comment by YiranWangPARC14** [comment]
Yes, that sounds good. Thanks for the suggestion!

Yiran

On Thu, Nov 19, 2015 at 1:16 PM, apoller <notifications@github.com> wrote:

> What about "Study Note"? Would avoid mistakes in my opinion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/secure-software-engineering/rose/issues/195#issuecomment-158200616>
> .
>



-- 
Best,
Yiran

**Comment by dharma-guardian** [comment]
Other options would be "remark", "annotation" or instead of "study [note]", explicitly saying "ROSE [comment/note]".

**Comment by YiranWangPARC14** [comment]
I think "Study Notes" is clear.

**Comment by dharma-guardian** [comment]
Does not require any further actions.
