### ISSUE TITLE
UI language detection

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#25]
I don't understand how I can persuade ROSE to switch to Englisch.
However, the ROSE UI is german although the installed Firefox 25.0.1/Windows 7 is set to English. Even after log in into an English Facebook account, nothing changes.

It could also be helpful to have a dropdown at the configurations page, where I can choose between "Auto detect", "Deutsch", "English" to manually change the language or to switch back to the (inproper) lanugage detection mechanism.

**Comment by dharma-guardian** [comment]
The language of the Facebook UI is auto-detected by the following parameters.
1) querystring parameter (?setLng=en-US)
2) cookie (i18next)
3) language set in navigator
from: http://i18next.com/pages/doc_init.html

The language can now be changed by the user in RoseUI, since e4bd71ed1be4a006fff0cd20052b287614652a02

Rose UI has a defined fallback of "en".
Missing is just an option "auto detect" in ROSE UI. Please add it Oliver to close this issue.

**Comment by dharma-guardian** [comment]
Added auto detect here: d7c6d3be2da31d3882328ddeafad3dddc4a1d879
