### ISSUE TITLE
Chrome store readiness: add a deactivate tracking toggle swich on Dashboard

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#268]

**Comment by eppfel** [comment]
So far, the tracking would proceed in tabs with content scripts.
Either I reload the relevant tabs, so the content scripts are not active or I implement a check during write procedure.
@iamolivinius Any thoughts?

**Comment by iamolivinius** [comment]
I'd argue that triggering a reload action would result in a bad user experience because of its destructive behavior. 
Implementing a write guard to "deactivate tracking" smells a bit funny, too.

In my opinion, the cleanest way would be to have an application state object where you can store references to trackers, eventlisteners, etc. If you have this you can programmatically shut down things.

**Comment by eppfel** [comment]
Yes, I saw both your points, but no other option. Thx, for that. I have to see, how much this would be to implement.

**Comment by eppfel** [comment]
6f6967bb7d6b4ce118a8400ecf48763be979774a
